### ISSUE TITLE
Incompatible with optifabric

### ISSUE THREAD

**Issue by pofice** [FoundationGames/Automobility#81]

**Comment by samuelh2005** [comment]
Optifine is known to break mods. In addition Optifine is closed source which makes it impossible to diagnose problems caused by Optifine. As a result, many mods do not work with Optifine and many people recommend using alternatives.

Since your on Fabric you can use Sodium and Iris. Those mods are both open source and do work with Automobility. Iris works with nearly all Optifine shaders, so you won't have too many problems there.
