### ISSUE TITLE
Client cannot start with create-1.18.2-0.5.0c-683

### ISSUE THREAD

**Issue by Mikm159** [FoundationGames/Automobility#9]
When the client only loads Automobility, everything is normal. However, when Automobility and create-1.18.2-0.5.0c-683 load at the same time, the client crashes
[minecraft-exported-logs-2022-08-11T23-28-16.log](https://github.com/FoundationGames/Automobility/files/9309869/minecraft-exported-logs-2022-08-11T23-28-16.log)
.

**Comment by Mikm159** [comment]
I guess the question comes from Myron. In fact, Create is not very compatible with Myron. I just found that this mod uses Myron.

**Comment by FoundationGames** [comment]
A dirty fix has been added (make Myron ignore all resources under `create`) in beta 0.1.1
This should instead be fixed by Myron, and once a compatible version of Myron is released, the dirty fix will be removed.

**Comment by TofuToons** [comment]
The dirty fix does not seem to work. Still looping on load up with both create 0.5 and Automobility installed.

**Comment by FoundationGames** [comment]
Are you using Automobility 0.1.1?
If so, please provide a log *and crash report* (the latter is where the error ends up for whatever reason)

**Comment by TofuToons** [comment]
Create Version: create-1.18.2-0.5.0c-708
Automobility Version: automobility-0.1.1+1.18.2

Instead of a crash, I get a loop on the loading screen. With the mod "pling" installed, I can hear the pling suggesting the loading is done, but then it starts loading again. I also had this issue with ShetiPhianCore which also uses Myron.

Because of this looping, I don't seem to get a crash report. Might be a performance or QoL mod making my game reload instead of crash. Not sure. But I will share my log below:
[latest.log](https://github.com/FoundationGames/Automobility/files/9314061/latest.log)


Theres some other errors in there, but Im fairly certain its the model loading errors from create.

**Comment by FoundationGames** [comment]
Does this occur with only Automobility and Create?
If not, it's more than likely an issue with another mod, and it's really hard to tell what mod is causing the error since lots of mods are spamming a lot of information (which often is unrelated to the actual error)

**Comment by TofuToons** [comment]
So after a lengthy process of elimination, I have located the incompatibility and it is:

Chimes! lol

Chimes Version: Chimes-1.1.1-1.18.2+[Fabric]

Just having Chimes and Automobility will cause the loading to constantly loop

Non informative log:
[latest.log](https://github.com/FoundationGames/Automobility/files/9314492/latest.log)

**Comment by TofuToons** [comment]
Ill open a new issue, since this no longer relates to this issue.
